from bs4 import BeautifulSoup

# open page source downloaded into HTML file
with open("/Users/drakeandersen/list_of_experimental_musicians.html") as fp:
	soup = BeautifulSoup(fp, 'html.parser')

# gives contents of all <li> tags
soup.find_all('li')

# gives list of artists
for tag in soup.ul.find_all("li", recursive=True):
	name = tag.text.split(" –", 1)
	print(name[0])

# en-dash is used as delimiter between artist name and descriptive text

# gather links to artist wiki pages
for link in soup.find_all('a'):
	print(link.get('href'))

# this requires some cleaning since there are additional links

# format as list (I used Excel to enclose in '' and append commas)

# final list of all sites
sites = ['https://en.wikipedia.org/wiki/Mohamed_Abdelwahab_Abdelfattah', 
'https://en.wikipedia.org/wiki/Acid_Mothers_Temple', 
'https://en.wikipedia.org/wiki/Arca_(musician)', 
'https://en.wikipedia.org/wiki/Alarm_Will_Sound', 
'https://en.wikipedia.org/wiki/Miguel_%C3%81lvarez-Fern%C3%A1ndez', 
'https://en.wikipedia.org/wiki/Giulio_Aldinucci', 
'https://en.wikipedia.org/wiki/Tori_Amos', 
'https://en.wikipedia.org/wiki/Laurie_Anderson', 
'https://en.wikipedia.org/wiki/Ron_Anderson_(musician)', 
'https://en.wikipedia.org/wiki/Animal_Collective', 
'https://en.wikipedia.org/wiki/Fr%C3%A9d%C3%A9ric_Acquaviva', 
'https://en.wikipedia.org/wiki/Robert_Ashley', 
'https://en.wikipedia.org/wiki/Cities_Aviv', 
'https://en.wikipedia.org/wiki/Nigel_Ayers', 
'https://en.wikipedia.org/wiki/Derek_Bailey_(guitarist)', 
'https://en.wikipedia.org/wiki/Beck', 
'https://en.wikipedia.org/wiki/David_Behrman', 
'https://en.wikipedia.org/wiki/Bj%C3%B6rk', 
'https://en.wikipedia.org/wiki/Boards_of_Canada', 
'https://en.wikipedia.org/wiki/Boredoms', 
'https://en.wikipedia.org/wiki/Burkhard_Beins', 
'https://en.wikipedia.org/wiki/Kate_Bush', 
'https://en.wikipedia.org/wiki/Buckethead', 
'https://en.wikipedia.org/wiki/Butthole_Surfers', 
'https://en.wikipedia.org/wiki/Glenn_Branca', 
'https://en.wikipedia.org/wiki/George_Brecht', 
'https://en.wikipedia.org/wiki/Bull_of_Heaven_(band)', 
'https://en.wikipedia.org/wiki/Gavin_Bryars', 
'https://en.wikipedia.org/wiki/John_Cage', 
'https://en.wikipedia.org/wiki/Can_(band)', 
'https://en.wikipedia.org/wiki/Captain_Beefheart', 
'https://en.wikipedia.org/wiki/Charli_XCX', 
'https://en.wikipedia.org/wiki/Cornelius_Cardew', 
'https://en.wikipedia.org/wiki/Rhys_Chatham', 
'https://en.wikipedia.org/wiki/Clipping.', 
'https://en.wikipedia.org/wiki/Coil_(band)', 
'https://en.wikipedia.org/wiki/Nicolas_Collins', 
'https://en.wikipedia.org/wiki/Loren_Mazzacane_Connors', 
'https://en.wikipedia.org/wiki/Controlled_Bleeding', 
'https://en.wikipedia.org/wiki/David_Cope', 
'https://en.wikipedia.org/wiki/Henry_Cowell', 
'https://en.wikipedia.org/wiki/Alvin_Curran', 
'https://en.wikipedia.org/wiki/Current_93', 
'https://en.wikipedia.org/wiki/Chris_Cutler', 
'https://en.wikipedia.org/wiki/Dead_Air_Fresheners', 
'https://en.wikipedia.org/wiki/Death_Grips', 
'https://en.wikipedia.org/wiki/Deftones', 
'https://en.wikipedia.org/wiki/Stuart_Dempster', 
'https://en.wikipedia.org/wiki/The_Dillinger_Escape_Plan', 
'https://en.wikipedia.org/wiki/Arnold_Dreyblatt', 
'https://en.wikipedia.org/wiki/Kevin_Drumm', 
'https://en.wikipedia.org/wiki/Iancu_Dumitrescu', 
'https://en.wikipedia.org/wiki/Judy_Dunaway', 
'https://en.wikipedia.org/wiki/Kyle_Bobby_Dunn', 
'https://en.wikipedia.org/wiki/Trevor_Dunn', 
'https://en.wikipedia.org/wiki/Marc_Edwards_(drummer)', 
'https://en.wikipedia.org/wiki/Leif_Elggren', 
'https://en.wikipedia.org/wiki/Brian_Eno', 
'https://en.wikipedia.org/wiki/Experimental_Audio_Research', 
'https://en.wikipedia.org/wiki/Carolina_Eyck', 
'https://en.wikipedia.org/wiki/Jean-Baptiste_Favory', 
'https://en.wikipedia.org/wiki/Florian-Ayala_Fauna', 
'https://en.wikipedia.org/wiki/FKA_Twigs', 
'https://en.wikipedia.org/wiki/Morton_Feldman', 
'https://en.wikipedia.org/wiki/Flume_(musician)', 
'https://en.wikipedia.org/wiki/Grimes_(musician)', 
'https://en.wikipedia.org/wiki/The_Flying_Lizards', 
'https://en.wikipedia.org/wiki/Flying_Lotus', 
'https://en.wikipedia.org/wiki/Henry_Flynt', 
'https://en.wikipedia.org/wiki/David_First', 
'https://en.wikipedia.org/wiki/John_Frusciante', 
'https://en.wikipedia.org/wiki/Cor_Fuhler', 
'https://en.wikipedia.org/wiki/Ellen_Fullman', 
'https://en.wikipedia.org/wiki/Diamanda_Gal%C3%A1s', 
'https://en.wikipedia.org/wiki/Qubais_Reed_Ghazala', 
'https://en.wikipedia.org/wiki/Philip_Glass', 
'https://en.wikipedia.org/wiki/Percy_Grainger', 
'https://en.wikipedia.org/wiki/Bruce_Haack', 
'https://en.wikipedia.org/wiki/Half_Japanese', 
'https://en.wikipedia.org/wiki/Richard_D._James_(musician)', 
'https://en.wikipedia.org/wiki/The_Hafler_Trio', 
'https://en.wikipedia.org/wiki/Lou_Harrison', 
'https://en.wikipedia.org/wiki/Carl_Michael_von_Hausswolff', 
'https://en.wikipedia.org/wiki/Joseph_Haydn', 
'https://en.wikipedia.org/wiki/Pierre_Henry', 
'https://en.wikipedia.org/wiki/Lejaren_Hiller', 
'https://en.wikipedia.org/wiki/Susumu_Hirasawa', 
'https://en.wikipedia.org/wiki/Christopher_Hobbs', 
'https://en.wikipedia.org/wiki/Tim_Hodgkinson', 
'https://en.wikipedia.org/wiki/Gustav_Holst', 
'https://en.wikipedia.org/wiki/Emily_Howell', 
'https://en.wikipedia.org/wiki/The_Hub_(band)', 
'https://en.wikipedia.org/wiki/I_Set_My_Friends_on_Fire', 
'https://en.wikipedia.org/wiki/Mart%C3%ADn_Irigoyen', 
'https://en.wikipedia.org/wiki/Charles_Ives', 
'https://en.wikipedia.org/wiki/Don_Joyce_(musician)', 
'https://en.wikipedia.org/wiki/Iwrestledabearonce', 
'https://en.wikipedia.org/wiki/KK_Null', 
'https://en.wikipedia.org/wiki/Kommissar_Hjuler', 
'https://en.wikipedia.org/wiki/Vladan_Kuzmanovi%C4%87', 
'https://en.wikipedia.org/wiki/Anne_La_Berge', 
'https://en.wikipedia.org/wiki/Andr%C3%A9_%C3%89ric_L%C3%A9tourneau', 
'https://en.wikipedia.org/wiki/George_Lewis_(trombonist)', 
'https://en.wikipedia.org/wiki/Steve_Lieberman', 
'https://en.wikipedia.org/wiki/A_Life_of_Science', 
'https://en.wikipedia.org/wiki/Lightning_Bolt_(band)', 
'https://en.wikipedia.org/wiki/Franz_Liszt', 
'https://en.wikipedia.org/wiki/Annea_Lockwood', 
'https://en.wikipedia.org/wiki/Alvin_Lucier', 
'https://en.wikipedia.org/wiki/John_Lydon', 
'https://en.wikipedia.org/wiki/The_Mars_Volta', 
'https://en.wikipedia.org/wiki/Elio_Martusciello', 
'https://en.wikipedia.org/wiki/Melvins', 
'https://en.wikipedia.org/wiki/Meshuggah', 
'https://en.wikipedia.org/wiki/Mama_Baer', 
'https://en.wikipedia.org/wiki/Miya_Masaoka', 
'https://en.wikipedia.org/wiki/Merzbow', 
'https://en.wikipedia.org/wiki/Moondog', 
'https://en.wikipedia.org/wiki/Gordon_Mumma', 
'https://en.wikipedia.org/wiki/Roberto_Musci', 
'https://en.wikipedia.org/wiki/Muslimgauze', 
'https://en.wikipedia.org/wiki/Ben_Neill', 
'https://en.wikipedia.org/wiki/Phill_Niblock', 
'https://en.wikipedia.org/wiki/Nocturnal_Emissions', 
'https://en.wikipedia.org/wiki/Nurse_With_Wound', 
'https://en.wikipedia.org/wiki/Michael_Nyman', 
'https://en.wikipedia.org/wiki/The_Observatory_(band)', 
'https://en.wikipedia.org/wiki/Obsil', 
'https://en.wikipedia.org/wiki/Olivier_Messiaen', 
'https://en.wikipedia.org/wiki/Pauline_Oliveros', 
'https://en.wikipedia.org/wiki/Yoko_Ono', 
'https://en.wikipedia.org/wiki/Orange_Monkey', 
'https://en.wikipedia.org/wiki/Ortiz_Morales', 
'https://en.wikipedia.org/wiki/John_Oswald_(composer)', 
'https://en.wikipedia.org/wiki/Nam_June_Paik', 
'https://en.wikipedia.org/wiki/Paul_Panhuysen', 
'https://en.wikipedia.org/wiki/Evan_Parker', 
'https://en.wikipedia.org/wiki/Harry_Partch', 
'https://en.wikipedia.org/wiki/Portishead_(band)', 
'https://en.wikipedia.org/wiki/Henri_Pousseur', 
'https://en.wikipedia.org/wiki/Radiohead', 
'https://en.wikipedia.org/wiki/A.R.Rahman', 
'https://en.wikipedia.org/wiki/Steve_Reich', 
'https://en.wikipedia.org/wiki/Hans_Reichel', 
'https://en.wikipedia.org/wiki/Renaldo_and_the_Loaf', 
'https://en.wikipedia.org/wiki/Dino_Residbegovic', 
'https://en.wikipedia.org/wiki/The_Residents', 
'https://en.wikipedia.org/wiki/Boyd_Rice', 
'https://en.wikipedia.org/wiki/Terry_Riley', 
'https://en.wikipedia.org/wiki/Cipriano_de_Rore', 
'https://en.wikipedia.org/wiki/David_Rosenboom', 
'https://en.wikipedia.org/wiki/Keith_Rowe', 
'https://en.wikipedia.org/wiki/Luigi_Russolo', 
'https://en.wikipedia.org/wiki/Kristoffer_Rygg', 
'https://en.wikipedia.org/wiki/Erik_Satie', 
'https://en.wikipedia.org/wiki/Pierre_Schaeffer', 
'https://en.wikipedia.org/wiki/Mathias_Rehfeldt', 
'https://en.wikipedia.org/wiki/Giancarlo_Schiaffini', 
'https://en.wikipedia.org/wiki/Elliott_Sharp', 
'https://en.wikipedia.org/wiki/Mark_Stanley_(guitarist)', 
'https://en.wikipedia.org/wiki/Solage', 
'https://en.wikipedia.org/wiki/Sonic_Youth', 
'https://en.wikipedia.org/wiki/Soul_Coughing', 
'https://en.wikipedia.org/wiki/Howard_Stelzer', 
'https://en.wikipedia.org/wiki/Sunn_O)))', 
'https://en.wikipedia.org/wiki/Svoy', 
'https://en.wikipedia.org/wiki/Swans_(band)', 
'https://en.wikipedia.org/wiki/Toru_Takemitsu', 
'https://en.wikipedia.org/wiki/James_Tenney', 
'https://en.wikipedia.org/wiki/They_Might_Be_Giants_(band)', 
'https://en.wikipedia.org/wiki/Lynda_Thomas', 
'https://en.wikipedia.org/wiki/Throbbing_Gristle', 
'https://en.wikipedia.org/wiki/Jason_van_Wyk', 
'https://en.wikipedia.org/wiki/Edgard_Var%C3%A8se', 
'https://en.wikipedia.org/wiki/Michael_Waller', 
'https://en.wikipedia.org/wiki/Ween', 
'https://en.wikipedia.org/wiki/Xiu_Xiu', 
'https://en.wikipedia.org/wiki/Kathleen_Yearwood', 
'https://en.wikipedia.org/wiki/La_Monte_Young', 
'https://en.wikipedia.org/wiki/Richard_Youngs', 
'https://en.wikipedia.org/wiki/Frank_Zappa', 
'https://en.wikipedia.org/wiki/Evan_Ziporyn', 
'https://en.wikipedia.org/wiki/John_Zorn', 
'https://en.wikipedia.org/wiki/Zoviet_France']
